# **Ejercicio 5 - Incorporación de datos adicionales**

En este ejercicio se amplía el sistema para incorporar los datos de 2024 de taxis amarillos y verdes, obteniéndolos directamente desde la fuente oficial de la TLC con el mismo script de descarga.

## **5.1 Modificación del sistema de descarga**

Dado que en el Ejercicio 2 el script ya se modificó para recibir el año como argumento (`--anio`), no fue necesario reescribirlo ni crear un segundo script para 2024. La única modificación fue actualizar los años que se descargan por defecto, de tal forma que al ejecutar el script sin argumentos se obtengan los años que utiliza el laboratorio:

```python
ANIOS_POR_DEFECTO = (2024, 2026)  # anios que utiliza el laboratorio
```

De esta forma, cualquier persona que clone el repositorio obtiene el mismo conjunto de datos con un solo comando, y para incorporar un nuevo año basta con agregarlo a esta tupla o indicarlo con `--anio`.

In [1]:
!python ../scripts/download_data.py --help

usage: download_data.py [-h] [--taxi {yellow,green,all}]
                        [--anio ANIO [ANIO ...]]

Descarga los datos de taxis amarillos y verdes del NYC TLC.

options:
  -h, --help            show this help message and exit
  --taxi {yellow,green,all}
                        tipo de taxi a descargar (por defecto: all)
  --anio ANIO [ANIO ...]
                        uno o varios anios a descargar (por defecto: [2024,
                        2026])

## **5.2 Conservación de los archivos de 2026**

El script nunca elimina ni sobrescribe archivos existentes, por lo que los 16 archivos de 2026 descargados en el Ejercicio 2 se conservan. A continuación se listan antes de ejecutar la nueva descarga, y en la salida del 5.4 se observa que el script los omite.

In [2]:
from pathlib import Path

archivos_2026 = sorted(Path("../data/raw").glob("*/2026/*.parquet"))
print(f"Archivos de 2026 antes de la descarga: {len(archivos_2026)}")
for archivo in archivos_2026:
    print(f"  {archivo.relative_to('../data/raw')}")

Archivos de 2026 antes de la descarga: 16
  green/2026/green_tripdata_2026-01.parquet
  green/2026/green_tripdata_2026-02.parquet
  green/2026/green_tripdata_2026-03.parquet
  green/2026/green_tripdata_2026-04.parquet
  green/2026/green_tripdata_2026-05.parquet
  green/2026/green_tripdata_2026-06.parquet
  green/2026/green_tripdata_2026-07.parquet
  green/2026/green_tripdata_2026-08.parquet
  yellow/2026/yellow_tripdata_2026-01.parquet
  yellow/2026/yellow_tripdata_2026-02.parquet
  yellow/2026/yellow_tripdata_2026-03.parquet
  yellow/2026/yellow_tripdata_2026-04.parquet
  yellow/2026/yellow_tripdata_2026-05.parquet
  yellow/2026/yellow_tripdata_2026-06.parquet
  yellow/2026/yellow_tripdata_2026-07.parquet
  yellow/2026/yellow_tripdata_2026-08.parquet

## **5.3 Evitar descargas repetidas**

El script ya cumple con este punto desde el Ejercicio 2 (inciso 2.4), por lo que no fue necesario configurarlo nuevamente. Antes de consultar al servidor, se revisa si el archivo existe localmente y, de ser así, se omite:

```python
if destino.exists() and destino.stat().st_size > 0:
    print(f"  {etiqueta}  ya existe, se omite")
    resumen["omitidos"] += 1
    continue
```

## **5.4 Ejecución del proceso de descarga**

Se ejecuta el script sin argumentos, por lo que descarga los años por defecto (2024 y 2026). En la salida se observa que se descargan los archivos de 2024, mientras que los de 2026 se omiten por existir previamente.

In [3]:
!python ../scripts/download_data.py

=== YELLOW 2024 ===

  2024-01  descargando...

  2024-01  listo (47.6 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-01.parquet

  2024-02  descargando...

  2024-02  listo (48.0 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-02.parquet

  2024-03  descargando...

  2024-03  listo (57.3 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-03.parquet

  2024-04  descargando...

  2024-04  listo (56.4 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-04.parquet

  2024-05  descargando...

  2024-05  listo (59.7 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-05.parquet

  2024-06  descargando...

  2024-06  listo (57.1 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-06.parquet

  2024-07  descargando...

  2024-07  listo (49.9 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-07.parquet

  2024-08  descargando...

  2024-08  listo (48.7 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-08.parquet

  2024-09  descargando...

  2024-09  listo (58.3 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-09.parquet

  2024-10  descargando...

  2024-10  listo (61.4 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-10.parquet

  2024-11  descargando...

  2024-11  listo (57.8 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-11.parquet

  2024-12  descargando...

  2024-12  listo (58.7 MiB) -> /workspace/data/raw/yellow/2024/yellow_tripdata_2024-12.parquet

=== GREEN 2024 ===

  2024-01  descargando...

  2024-01  listo (1.3 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-01.parquet

  2024-02  descargando...

  2024-02  listo (1.2 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-02.parquet

  2024-03  descargando...

  2024-03  listo (1.3 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-03.parquet

  2024-04  descargando...

  2024-04  listo (1.3 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-04.parquet

  2024-05  descargando...

  2024-05  listo (1.4 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-05.parquet

  2024-06  descargando...

  2024-06  listo (1.3 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-06.parquet

  2024-07  descargando...

  2024-07  listo (1.2 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-07.parquet

  2024-08  descargando...

  2024-08  listo (1.2 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-08.parquet

  2024-09  descargando...

  2024-09  listo (1.3 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-09.parquet

  2024-10  descargando...

  2024-10  listo (1.3 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-10.parquet

  2024-11  descargando...

  2024-11  listo (1.2 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-11.parquet

  2024-12  descargando...

  2024-12  listo (1.3 MiB) -> /workspace/data/raw/green/2024/green_tripdata_2024-12.parquet

=== YELLOW 2026 ===
  2026-01  ya existe, se omite
  2026-02  ya existe, se omite
  2026-03  ya existe, se omite
  2026-04  ya existe, se omite
  2026-05  ya existe, se omite
  2026-06  ya existe, se omite
  2026-07  ya existe, se omite
  2026-08  ya existe, se omite

  2026-09  aun no publicado por la TLC

  2026-10  aun no publicado por la TLC

  2026-11  aun no publicado por la TLC

  2026-12  aun no publicado por la TLC

=== GREEN 2026 ===
  2026-01  ya existe, se omite
  2026-02  ya existe, se omite
  2026-03  ya existe, se omite
  2026-04  ya existe, se omite
  2026-05  ya existe, se omite
  2026-06  ya existe, se omite
  2026-07  ya existe, se omite
  2026-08  ya existe, se omite

  2026-09  aun no publicado por la TLC

  2026-10  aun no publicado por la TLC

  2026-11  aun no publicado por la TLC

  2026-12  aun no publicado por la TLC

============================================================
RESUMEN
============================================================
  anios         : 2024, 2026
  destino       : /workspace/data/raw
  descargados   : 24
  ya existian   : 16
  no publicados : 8
      yellow 2026-09, yellow 2026-10, yellow 2026-11, yellow 2026-12, green 2026-09, green 2026-10, green 2026-11, green 2026-12
  fallidos      : 0
============================================================

## **5.5 Verificación de los nuevos archivos**

Se aplicaron las mismas validaciones del Ejercicio 2 a los archivos de 2024. Primero, a nivel de archivos, se comprobó contra el servidor de la TLC que los 24 archivos publicados (12 meses para cada tipo de taxi) existen localmente, tienen el mismo tamaño que informa el servidor y se pueden leer como Parquet. Luego, a nivel de contenido, se verificó con DuckDB que cada archivo tenga registros y que más del 99.9 % de sus viajes corresponda al mes que indica su nombre. En total se incorporaron 41,169,720 viajes de taxis amarillos y 660,218 de taxis verdes.

In [4]:
import sys

import duckdb
import pandas as pd
import pyarrow.parquet as pq

sys.path.insert(0, str(Path("../scripts").resolve()))
import download_data as dd

ANIO_NUEVO = 2024
filas = []
for tipo in dd.TIPOS_TAXI:
    for mes in range(1, 13):
        estado, tamanio_servidor, _ = dd.consultar_publicacion(dd.construir_url(tipo, ANIO_NUEVO, mes))
        ruta = dd.ruta_destino(tipo, ANIO_NUEVO, mes)
        existe = ruta.exists()
        filas.append({
            "tipo": tipo,
            "mes": f"{ANIO_NUEVO}-{mes:02d}",
            "estado_servidor": estado,
            "existe_local": existe,
            "tamanio_local": ruta.stat().st_size if existe else None,
            "tamanio_servidor": tamanio_servidor,
            "filas": pq.ParquetFile(ruta).metadata.num_rows if existe else None,
        })

verificacion = pd.DataFrame(filas).astype(
    {"tamanio_local": "Int64", "tamanio_servidor": "Int64", "filas": "Int64"}
)
verificacion["coincide"] = (verificacion["tamanio_local"] == verificacion["tamanio_servidor"]).astype("boolean")

assert (verificacion["estado_servidor"] == dd.PUBLICADO).all(), "No todos los meses de 2024 están publicados"
assert verificacion["existe_local"].all(), "Falta descargar algún mes de 2024"
assert verificacion["coincide"].all(), "Algún archivo no coincide con el tamaño del servidor"
print(f"[ok] {len(verificacion)} archivos de {ANIO_NUEVO} descargados y con el tamaño del servidor")
verificacion

[ok] 24 archivos de 2024 descargados y con el tamaño del servidor

,tipo,mes,estado_servidor,existe_local,tamanio_local,tamanio_servidor,filas,coincide
0,yellow,2024-01,publicado,True,49961641,49961641,2964624,True
1,yellow,2024-02,publicado,True,50349284,50349284,3007526,True
2,yellow,2024-03,publicado,True,60078280,60078280,3582628,True
3,yellow,2024-04,publicado,True,59133625,59133625,3514289,True
4,yellow,2024-05,publicado,True,62553128,62553128,3723833,True
5,yellow,2024-06,publicado,True,59859922,59859922,3539193,True
6,yellow,2024-07,publicado,True,52299432,52299432,3076903,True
7,yellow,2024-08,publicado,True,51067350,51067350,2979183,True
8,yellow,2024-09,publicado,True,61170186,61170186,3633030,True
9,yellow,2024-10,publicado,True,64346071,64346071,3833771,True
10,yellow,2024-11,publicado,True,60658709,60658709,3646369,True
11,yellow,2024-12,publicado,True,61524085,61524085,3668371,True
12,green,2024-01,publicado,True,1362284,1362284,56551,True
13,green,2024-02,publicado,True,1283805,1283805,53577,True
14,green,2024-03,publicado,True,1372372,1372372,57457,True
15,green,2024-04,publicado,True,1346502,1346502,56471,True
16,green,2024-05,publicado,True,1453912,1453912,61003,True
17,green,2024-06,publicado,True,1326194,1326194,54748,True
18,green,2024-07,publicado,True,1250973,1250973,51837,True
19,green,2024-08,publicado,True,1267079,1267079,51771,True
20,green,2024-09,publicado,True,1326186,1326186,54440,True
21,green,2024-10,publicado,True,1353731,1353731,56147,True
22,green,2024-11,publicado,True,1264688,1264688,52222,True
23,green,2024-12,publicado,True,1312306,1312306,53994,True

In [5]:
con = duckdb.connect()

cobertura = con.sql(r"""
    WITH viajes AS (
        SELECT regexp_extract(filename, '(yellow|green)_tripdata', 1)        AS tipo,
               regexp_extract(filename, '_(\d{4}-\d{2})\.parquet', 1)      AS mes_archivo,
               strftime(COALESCE(tpep_pickup_datetime, lpep_pickup_datetime), '%Y-%m') AS mes_viaje
        FROM read_parquet('../data/raw/*/2024/*.parquet', filename = true, union_by_name = true)
    )
    SELECT tipo,
           mes_archivo,
           COUNT(*)                                                                      AS viajes,
           ROUND(100.0 * COUNT(*) FILTER (WHERE mes_viaje <> mes_archivo) / COUNT(*), 4) AS pct_fuera_del_mes
    FROM viajes
    GROUP BY tipo, mes_archivo
    ORDER BY tipo DESC, mes_archivo
""").df()

assert (cobertura["viajes"] > 0).all(), "Hay archivos sin registros"
assert (cobertura["pct_fuera_del_mes"] < 0.1).all(), "Algún archivo tiene muchos viajes fuera de su mes"
print(f"[ok] {len(cobertura)} archivos con registros y viajes dentro de su mes")
print(cobertura.groupby("tipo", sort=False)["viajes"].sum().to_string())
cobertura

[ok] 24 archivos con registros y viajes dentro de su mes
tipo
yellow    41169720
green       660218

      tipo mes_archivo   viajes  pct_fuera_del_mes
0   yellow     2024-01  2964624             0.0006
1   yellow     2024-02  3007526             0.0005
2   yellow     2024-03  3582628             0.0006
3   yellow     2024-04  3514289             0.0003
4   yellow     2024-05  3723833             0.0009
5   yellow     2024-06  3539193             0.0014
6   yellow     2024-07  3076903             0.0015
7   yellow     2024-08  2979183             0.0017
8   yellow     2024-09  3633030             0.0013
9   yellow     2024-10  3833771             0.0010
10  yellow     2024-11  3646369             0.0014
11  yellow     2024-12  3668371             0.0009
12   green     2024-01    56551             0.0035
13   green     2024-02    53577             0.0112
14   green     2024-03    57457             0.0174
15   green     2024-04    56471             0.0071
16   green     2024-05    61003             0.0148
17   green     2024-06    54748             0.0237
18   green     2024-07    51837             0.0502
19   green     2024-08    51771             0.0386
20   green     2024-09    54440             0.0625
21   green     2024-10    56147             0.0125
22   green     2024-11    52222             0.0287
23   green     2024-12    53994             0.0333

## **5.6 Consulta conjunta de 2024 y 2026**

Con DuckDB es posible consultar ambos años en una sola consulta, ya que basta con que la ruta utilice un comodín en la carpeta del año (`data/raw/*/*/*.parquet`). La siguiente consulta obtiene, para cada año y tipo de taxi, la cantidad de viajes, los meses disponibles, la distancia mediana y el monto total mediano. Por ejemplo, se observa que en 2026 el monto mediano de un viaje amarillo subió de 21.00 a 23.58 dólares respecto a 2024, y que los taxis verdes pasaron de alrededor de 55 mil a 42 mil viajes por mes.

In [6]:
RUTA_TODOS = "../data/raw/*/*/*.parquet"

con.sql(f"""
    SELECT regexp_extract(filename, '_(\\d{{4}})-', 1)                      AS anio,
           regexp_extract(filename, '(yellow|green)_tripdata', 1)            AS tipo,
           COUNT(*)                                                          AS viajes,
           COUNT(DISTINCT regexp_extract(filename, '_(\\d{{4}}-\\d{{2}})\\.parquet', 1)) AS meses,
           ROUND(COUNT(*) / COUNT(DISTINCT regexp_extract(filename, '_(\\d{{4}}-\\d{{2}})\\.parquet', 1))) AS viajes_por_mes,
           ROUND(MEDIAN(trip_distance), 2)                                   AS distancia_mediana,
           ROUND(MEDIAN(total_amount), 2)                                    AS total_mediano
    FROM read_parquet('{RUTA_TODOS}', filename = true, union_by_name = true)
    GROUP BY anio, tipo
    ORDER BY anio, tipo DESC
""").df()

,anio,tipo,viajes,meses,viajes_por_mes,distancia_mediana,total_mediano
0,2024,yellow,41169720,12,3430810.0,1.76,21.00
1,2024,green,660218,12,55018.0,1.87,19.32
2,2026,yellow,29703355,8,3712919.0,1.86,23.58
3,2026,green,337114,8,42139.0,2.07,20.46

## **5.7 Ajustes necesarios en las consultas desarrolladas**

En general, las consultas desarrolladas no necesitan modificarse para trabajar con el nuevo conjunto de archivos, ya que leen los datos con comodines en las rutas y con `union_by_name`, de tal forma que los archivos de 2024 se incorporan automáticamente. Por ejemplo, las vistas `viajes` y `viajes_limpios` del Ejercicio 4 funcionan sin cambios sobre ambos años, y la regla de limpieza de fechas compara contra el mes del archivo y no contra un año fijo. Sin embargo, al incorporar los nuevos archivos se identificaron los siguientes ajustes:

- **Esquema que cambia con el tiempo:** `cbd_congestion_fee` no existe en 2024 (el cobro inició en 2025) y `request_source` solo existe a partir de junio de 2026. Sin `union_by_name`, DuckDB toma únicamente el esquema del primer archivo e ignora estas columnas, por lo que se corrigieron los `DESCRIBE` de los incisos 3.3 y 3.4 para utilizarlo.
- **Año fijo en algunas reglas:** la regla `year(pickup) <> 2026` del inciso 3.6 y la verificación del Ejercicio 2 tienen el año escrito en el código, por lo que para otros años se debe utilizar la regla basada en el mes del archivo.
- **Agregaciones que mezclan años:** consultas como las de día de la semana, hora o percentiles agrupan todos los registros, por lo que al tener varios años se debe agregar el año al `GROUP BY` para no mezclar periodos.
- **Notebooks del análisis de 2026:** los Ejercicios 3 y 4 documentan resultados de 2026, por lo que se fijó su ruta a `data/raw/*/2026/*.parquet` mediante una constante `ANIO`. De esta forma, si se vuelven a ejecutar, siguen produciendo los mismos resultados, que se verificó ejecutándolos nuevamente después de descargar 2024.

In [7]:
# Columnas que no existen en todos los archivos de un mismo tipo de taxi
con.sql(f"""
    WITH esquema AS (
        SELECT regexp_extract(file_name, '(yellow|green)_tripdata', 1) AS tipo,
               regexp_extract(file_name, '_(\\d{{4}})-', 1)           AS anio,
               file_name,
               name                                                   AS columna
        FROM parquet_schema('{RUTA_TODOS}')
        WHERE name <> 'schema'
    ),
    archivos_por_tipo AS (
        SELECT tipo, COUNT(DISTINCT file_name) AS archivos_totales
        FROM esquema
        GROUP BY tipo
    )
    SELECT e.tipo,
           e.columna,
           string_agg(DISTINCT e.anio, ', ' ORDER BY e.anio)  AS anios_con_la_columna,
           COUNT(DISTINCT e.file_name)                        AS archivos_con_la_columna,
           a.archivos_totales
    FROM esquema e
    JOIN archivos_por_tipo a USING (tipo)
    GROUP BY e.tipo, e.columna, a.archivos_totales
    HAVING COUNT(DISTINCT e.file_name) < a.archivos_totales
    ORDER BY e.tipo DESC, e.columna
""").df()

,tipo,columna,anios_con_la_columna,archivos_con_la_columna,archivos_totales
0,yellow,cbd_congestion_fee,2026,8,20
1,yellow,request_source,2026,3,20
2,green,cbd_congestion_fee,2026,8,20
3,green,request_source,2026,3,20

In [8]:
# Las vistas del Ejercicio 4, sin cambios, sobre todos los anios descargados
con.sql(f"""
    CREATE OR REPLACE VIEW viajes AS
    SELECT regexp_extract(filename, '(yellow|green)_tripdata', 1)         AS tipo,
           regexp_extract(filename, '_(\\d{{4}}-\\d{{2}})\\.parquet', 1) AS mes_archivo,
           COALESCE(tpep_pickup_datetime, lpep_pickup_datetime)            AS pickup,
           COALESCE(tpep_dropoff_datetime, lpep_dropoff_datetime)          AS dropoff,
           passenger_count IS NULL AND RatecodeID IS NULL                  AS sin_metadatos,
           *
    FROM read_parquet('{RUTA_TODOS}', filename = true, union_by_name = true)
""")
con.sql("""
    CREATE OR REPLACE VIEW viajes_limpios AS
    SELECT *,
           epoch(dropoff - pickup) / 60 AS duracion_min
    FROM viajes
    WHERE strftime(pickup, '%Y-%m') = mes_archivo
      AND dropoff > pickup AND dropoff - pickup <= INTERVAL 24 HOUR
      AND trip_distance > 0 AND trip_distance <= 100
      AND fare_amount >= 0 AND total_amount > 0
""")

con.sql("""
    SELECT year(pickup)                                            AS anio,
           COUNT(*)                                                AS viajes_limpios,
           ROUND(100 * AVG(sin_metadatos::INT), 1)                 AS pct_sin_metadatos,
           ROUND(MEDIAN(trip_distance), 2)                         AS distancia_mediana,
           ROUND(MEDIAN(duracion_min), 1)                          AS duracion_mediana_min
    FROM viajes_limpios
    GROUP BY anio
    ORDER BY anio
""").df()

,anio,viajes_limpios,pct_sin_metadatos,distancia_mediana,duracion_mediana_min
0,2024,40333166,9.2,1.80,13.1
1,2026,28563773,24.8,1.93,14.1

## **5.8 Documentación de las consultas de validación**

La siguiente tabla resume las consultas utilizadas para validar la incorporación de 2024. El SQL de cada una se encuentra en la celda de su inciso y, de forma consolidada, en [`../sql/ejercicio_5.sql`](../sql/ejercicio_5.sql).

| Consulta | Inciso | Objetivo | Archivos fuente | Resultado | Decisión |
|---|---|---|---|---|---|
| Q1 | 5.5 | Verificar que cada archivo de 2024 tenga registros y que sus viajes correspondan a su mes | `data/raw/*/2024/*.parquet` | 24 archivos con registros; más del 99.9 % de los viajes de cada archivo dentro de su mes | Se confirma que 2024 se incorporó completo |
| Q2 | 5.6 | Consultar de forma conjunta 2024 y 2026 por año y tipo de taxi | `data/raw/*/*/*.parquet` | Viajes, meses, distancia mediana y monto mediano por año y tipo | Se confirma que ambos años se consultan sin cambios en la ruta ni en la consulta |
| Q3 | 5.7 | Identificar las columnas que no existen en todos los archivos | Esquema de `data/raw/*/*/*.parquet` | `cbd_congestion_fee` falta en 2024 y `request_source` solo existe desde junio de 2026 | Utilizar `union_by_name` en todas las lecturas, incluyendo `DESCRIBE` |
| Q4 | 5.7 | Ejecutar las vistas del Ejercicio 4 sin cambios sobre ambos años | `data/raw/*/*/*.parquet` | Las vistas `viajes` y `viajes_limpios` funcionan para 2024 y 2026 | Agregar el año al `GROUP BY` en las agregaciones para no mezclar periodos |

## **5.9 Características del diseño que permiten incorporar nuevos archivos**

Considero que el sistema permite incorporar nuevos archivos sin modificar todo el flujo de análisis gracias a varias decisiones de diseño. Primero, el script de descarga recibe los años como parámetro (`--anio` y `ANIOS_POR_DEFECTO`) en lugar de tenerlos fijos en el código, y omite los archivos que ya existen, por lo que incorporar un año nuevo es cuestión de agregarlo y volver a ejecutar el mismo script, el cual solo descarga lo que falta. Además, el script trabaja con rutas resueltas a partir de su propia ubicación y guarda los archivos en una estructura predecible (`data/raw/<tipo>/<anio>/`), de tal forma que el resultado es el mismo sin importar desde dónde se ejecute.

Por otro lado, las consultas leen los archivos con comodines en la ruta y con `union_by_name`, por lo que DuckDB incorpora automáticamente los archivos nuevos y absorbe las columnas que la TLC agrega o elimina con el tiempo; asimismo, la lógica de unificación y limpieza está centralizada en las vistas `viajes` y `viajes_limpios`, por lo que no es necesario repetirla en cada consulta. Finalmente, todo se ejecuta dentro de un ambiente reproducible con Docker, lo que garantiza que cualquier persona del equipo obtenga los mismos resultados con las mismas versiones de las herramientas.